# Numpy explanation

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5,6]
arr=np.array(my_list)

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)#this is a one dimensional array

numpy.ndarray

In [8]:
arr.shape#tells the number of rows and columns of the array

(6,)

In [9]:
arr.size

6

In [32]:
l=[1,2,3,4,5,6]
m=[1,2,3,4,5,6]
n=[1,2,3,4,5,6]
arr=np.array([l,m,n])

In [33]:
arr

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [12]:
arr.shape

(3, 6)

In [13]:
arr.size#rows multiplied by column gives the size of the multidimensional array

18

In [34]:
arr.reshape(6,3)#transpose of the matrix

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.shape

(3, 6)

In [23]:
arr.size

18

In [35]:
arr[0][1]

2

In [36]:
arr[0:3][0:3]

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [37]:
arr=np.arange(0,15)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [45]:
arr[3:]=100#copy function 

In [46]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [47]:
arr1=arr.copy()

In [48]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [49]:
arr1.mean

<function ndarray.mean>

In [50]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [51]:
arr1.mean(axis=0)

80.2

In [52]:
arr1.min()

0

In [53]:
arr.max()

100

In [ ]:
arr.