##   WELCOME TO NUMPY TUTORIAL

In [7]:
import numpy as np

In [8]:
myarr=np.array([[3,6,32,7]],np.int8)


In [9]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myarr[0]

array([ 3,  6, 32,  7], dtype=int8)

In [5]:
myarr[0,1]

6

In [6]:
myarr.shape()

TypeError: 'tuple' object is not callable

In [ ]:
myarr.dtype

In [ ]:
myarr[0,1]

In [ ]:
myarr[0,1]=45


In [ ]:
myarr[0,1]

In [ ]:
myarr

# Array creation: Conversion from other Python structures 

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({23,44,33})

array({33, 44, 23}, dtype=object)

# Intrinsic NumPy array creation functions

In [16]:
zeros=np.zeros((2,5)) #it is used to add 0 to 2 dimensional array of the given size and order

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
zeros.size

10

In [21]:
rng = np.arange(15) #arange() function is used to create a array from n to n-1

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(0,5,5)#linspace function in numpy is used to give equally linearly space between 1 to 5

In [24]:
lspace

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810132e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.11261162e-306, 8.34443015e-308, 1.42404727e-306]])

In [27]:
emplike=np.empty_like(lspace)

In [28]:
emplike

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [29]:
ide=np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.size

2025

In [32]:
ide.shape

(45, 45)

In [33]:
arr=np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr=arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr.ravel()#to straighten the matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
np.arange(99)#prints array in 0 to n-1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr.shape

(3, 33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [43]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
arr=np.array(x)

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.sum(axis=0)#sum spanning through columns

array([12, 15, 18])

In [47]:
arr.sum(axis=1)#sum spanning through rows

array([ 6, 15, 24])

In [48]:
arr.T#to transpose the rows and the columns

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
arr.flat

In [50]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [51]:
arr.ndim #tells the dimension of the matrix

2

In [52]:
arr.nbytes

36

In [53]:
one=np.array([1,3,4,7,6])

In [54]:
one.argmax()#tells the idex of the array where maximum element is stored

3

In [55]:
one.argmin()#tells the index of the array where minimum value is stored

0

In [56]:
one.argsort()#tells the index where the maximum values are stored

array([0, 1, 2, 4, 3], dtype=int64)

In [57]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr.argsort()#tells the order of the indexes where the elements are arranged

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [59]:
arr.argmin()

0

In [60]:
arr.argmax()

8

In [61]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [62]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [63]:
arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [64]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)